# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\ww\wk\init\cvwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from deco import rptges

class Ui_MTU(object):
    def setupUi(self, MTU):
        MTU.setObjectName("MTU")
        MTU.resize(656, 152)
        MTU.setAcceptDrops(True)
        MTU.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MTU)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setStyleSheet("#centralwidget{background-color: rgb(170, 170, 127);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.labelinfo = QtWidgets.QLabel(self.frame_3)
        self.labelinfo.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelinfo.setText("")
        self.labelinfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelinfo.setObjectName("labelinfo")
        self.verticalLayout_5.addWidget(self.labelinfo)
        self.verticalLayout.addWidget(self.frame_3)
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(222, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.inpushButton = QtWidgets.QPushButton(self.frame_14)
        self.inpushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.inpushButton.setObjectName("inpushButton")
        self.horizontalLayout_8.addWidget(self.inpushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_14)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MTU.setCentralWidget(self.centralwidget)

        self.retranslateUi(MTU)
        QtCore.QMetaObject.connectSlotsByName(MTU)

    def retranslateUi(self, MTU):
        _translate = QtCore.QCoreApplication.translate
        MTU.setWindowTitle(_translate("MTU", "MTU"))
        self.label_10.setText(_translate("MTU", rptges("YGMgDFxO1apsXDcCwNgYzrng5woAlRUMcjWsZ4f8QFtou4MwMla1qhVl1MXEFp0jeWWDBiGANyTYDP+zsFbAOst5XntzRSEsDQnL7aYhbjk/R2pbl9DZywKxl4uk/BDE1vov7D8bjSwyOMhlDuvjqtDAvfxQVj5OU/XdfjQNSGG/Knzx/DLtyNmuRgIUZuW+9t/NTbF3tiw+YXlAoBnRPPUYXuXzYLjyJWDefTsxfaokolB4TKxbVXGVXxTYzd5LLuZh5Bt1kQnSAeCyBf33wK54sEO2uJLTJm0j7uhwqJclXBgkibOSdU4taDftcRvw4juHavP6OlBJMAMj7ea0bmx8rltoiuHYzG9acVGrEgZXJFZ0M5oiG2DDjw2OXGk1vXT0rC/+u8IDTiI=")))
        self.label.setText(_translate("MTU", rptges("uYPJhJf7DE6f28SbFkvNRWUUMZDxTXUDF2GKDmIUwrKtMH6cuItiIvyYXxZlixJNKlXkfhb4fxNvmgNEO9g/qDqF0+mYgonvi/wAeTGm7/eBl+DkQzB6GlqI")))
        self.inpushButton.setText(_translate("MTU", rptges("uYPJhJf7DE6f")))
